name: Ulrike Genschel
description: Assistant Professor at Iowa State University Statistics
url: http://ugenschel.github.io
auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
navigation:
- text: About
  id: "#one"
- text: CV
  id: /cv.pdf
- text: Research
  id: "#research"
- text: Students
  id: "#students"
- text: Teaching
  id: "#teaching"
- text: Miscellaneous
  id: "#miscellaneous"